Repository CKI-project/skt, pull requests merged in 2018-06, with the labels that each got.

#172 Allow the shell to expand the rc file path
  skt/executable.py
Labels: enhancement

#180 Docs: Explain kernel cfgtype options
  README.md
Labels: docs

#182 CircleCI: Remove unit/lint testing
  .circleci/config.yml
Labels: enhancement

#179 Add KernelBuilder test and tidy up docstrings
  tests/test_kernelbuilder.py
Labels: enhancement

#176 Travis-CI: Enable branch testing
  tox.ini
Labels: enhancement

#189 Refactor state file tests
  tests/test_state_file.py
Labels: enhancement

#190 Fix KernelTree tests
  tests/test_kerneltree.py
Labels: enhancement

#204 Remove tests directory from coverage
  tox.ini
Labels: bug

#209 Fix conditional in check_args()
  skt/executable.py
Labels: bug

#206 junit: Create directory if it doesn't exist
  skt/executable.py
Labels: enhancement

#207 Use command line args for report
  skt/executable.py
  skt/reporter.py
Labels: enhancement

#219 Set defaults for mail subject/header
  skt/executable.py
Labels: bug

#212 Add support for remote smtp url
  skt/executable.py
  skt/reporter.py
Labels: enhancement

#255 Add LTP lite reports on failures
  skt/reporter.py
  skt/runner.py
Labels: enhancement

#257 reporter: Skip run results for merge failure
  skt/reporter.py
Labels: bug

#240 merge: Convert multi-value options
  CHANGELOG.md
  README.md
  skt/executable.py
Labels: enhancement

#261 Fix merge command help output
  skt/executable.py
Labels: bug

#264 Include original trace of the exceptions
  skt/executable.py
Labels: bug

#263 Fix placing of binary operators
  skt/executable.py
Labels: enhancement

#249 reporter: Clean up load_state_cfg() docstring
  skt/reporter.py
Labels: bug
